---
  - src: git@github.com:maks1001281/lighthouse-role.git
    scm: git
    version: "v1.0.1"
    name: lighthouse
  - src: git@github.com:maks1001281/vector-role.git
    scm: git
    version: "v1.0.3"
    name: vector
  - src: git@github.com:maks1001281/Clickhouse-role.git
    scm: git
    version: "v1.0.0"
    name: clickhouse
