---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos7
    image: docker.io/library/centos:centos7.9.2009
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
